swagger: '2.0'
info:
  description: Employee Management REST API
  version: 1.0.0
  title: Employee Management REST API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: "ec2-52-5-221-93.compute-1.amazonaws.com:8080"
basePath: "/"
schemes:
- http

securityDefinitions:
  basicAuth:
    type: basic

security:
- basicAuth: [ ]

tags:
- name: employee-controller
  description: Operations pertaining to employee in Employee Management System

paths:
  /employees:
    get:
      tags:
      - employee-controller
      summary: View a list of available employees, require USER or ADMIN role
      operationId: getAllEmployees
      produces:
      - "application/json"
      responses:
        '200':
          description: Successfully retrieved list
          schema:
            type: array
            items:
              type: object
        '401':
          description: Authentication information is missing or invalid
        '403':
          description: Accessing the resource you were trying to reach is forbidden for your role
    post:
      tags:
      - employee-controller
      summary: Create employee, require ADMIN role
      operationId: createEmployee
      consumes:
      - application/json
      produces:
      - "application/json"
      parameters:
      - in: body
        name: employee
        description: Employee object store in database table
        required: true
        schema:
          "$ref": "#/definitions/Employee"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Employee"
        '401':
          description: Authentication information is missing or invalid
        '403':
          description: Accessing the resource you were trying to reach is forbidden for your role
        '409':
          description: Employee with username or emailId exists
        '422':
          description: Incorrect employee (entity fields are not valid)
  /employees/{id}:
    get:
      tags:
      - employee-controller
      summary: Get an employee by Id, require USER or ADMIN role
      operationId: getEmployeeById
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: Employee id from which employee object will retrieve
        required: true
        type: integer
        format: int64
      responses:
        '200':
          description: Successfully retrieved employee
          schema:
            "$ref": "#/definitions/Employee"
        '401':
          description: Authentication information is missing or invalid
        '403':
          description: Accessing the resource you were trying to reach is forbidden for your role
        '404':
          description: The employee you were trying to reach is not found
    put:
      tags:
      - employee-controller
      summary: Update an employee, require ADMIN role
      operationId: updateEmployee
      consumes:
      - application/json
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: Employee Id to update employee object
        required: true
        type: integer
        format: int64
      - in: body
        name: employeeDetails
        description: Update employee object
        required: true
        schema:
          "$ref": "#/definitions/Employee"
      responses:
        '200':
          description: Successfully updated employee
          schema:
            "$ref": "#/definitions/Employee"
        '401':
          description: Authentication information is missing or invalid
        '403':
          description: Accessing the resource you were trying to reach is forbidden for your role
        '404':
          description: The employee you were trying to reach is not found
        '409':
          description: Employee with username or emailId exists
        '422':
          description: Incorrect employee (entity fields are not valid)
    delete:
      tags:
      - employee-controller
      summary: Delete an employee, require ADMIN role
      operationId: deleteEmployee
      produces:
      - "application/json"
      parameters:
      - name: id
        in: path
        description: Employee Id from which employee object will delete from database
          table
        required: true
        type: integer
        format: int64
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: boolean
        '401':
          description: Authentication information is missing or invalid
        '403':
          description: Accessing the employee you were trying to reach is forbidden for your role
        '404':
          description: The employee you were trying to reach is not found
definitions:
  Employee:
    type: object
    required:
    - emailId
    - firstName
    - lastName
    - username
    properties:
      id:
        type: integer
        format: int64
        description: The database generated employee ID
        allowEmptyValue: false
      emailId:
        type: string
        description: The employee email id
        allowEmptyValue: false
      firstName:
        type: string
        description: The employee first name
        allowEmptyValue: false
      lastName:
        type: string
        description: The employee last name
        allowEmptyValue: false
      username:
        type: string
        description: The employee username
        allowEmptyValue: false
    title: Employee
    description: 'All details about the Employee. '
